server:
  port: 3306
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: djznxj2ttp
    url: jdbc:mysql://sql12.freesqldatabase.com:5432/sql12652073
    username: sql12652073
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: zxque9681@gmail.com
    password: kpdg oisb uldk hwpj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  twilio:
    account_sid: ACc2a522ebd3172b9f66ac39c838814f51
    auth_token: 3db836b47f6499cb4b8291ede670a688
    trial_number: +12314004777